language: c

os:
  - linux
  - osx

compiler: gcc
sudo: false
addons:
  apt:
    packages:
      - libpcap-dev
      - libzmq3-dev
  homebrew:
    update: true
    packages:
      - libpcap
      - zeromq

before_script: autoreconf -if
script: ./configure --enable-ntopng && make
